### ISSUE TITLE
Some tracks give this issues

### ISSUE THREAD

**Issue by mal1kc** [lukaszsulek/get_lyric#1]
song Özdemir Erdoğan -Aç Kapıyı Gir İçeri

Traceback (most recent call last):
  File "get_lyric.py", line 26, in <module>
    print(song.lyrics)
AttributeError: 'NoneType' object has no attribute 'lyrics'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "get_lyric.py", line 28, in <module>
    print(f"{sys.argv[2]} - {sys.argv[4]}\n\nLyrics not found")
  File "C:\Users\user\AppData\Local\Programs\Python\Python38\lib\encodings\cp1254.py", line 19, in encode
    return codecs.charmap_encode(input,self.errors,encoding_table)[0]
UnicodeEncodeError: 'charmap' codec can't encode character '\x96' in position 1: character maps to <undefined>

**Comment by lukaszsulek** [comment]
Hey Mmal1kK! 

Thanks for the feedback! The first issue where no song has been found has been fixed for a couple of weeks now in the latest iteration of the script.

For your second exception, please check out the "Known Issues" section in the readme as this is a common issue in general when running python in a windows environment.

Hopefully that sorts you out! Keep me posted!

**Comment by mal1kc** [comment]
I solve this problem with add "sys.stdout.reconfigure(encoding='utf-8')" to 9th line in get_lyric.py
